name: music-genre-classification
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - tqdm>=4.62.0
  - python-dotenv>=0.19.0
  - pydot>=1.4.0
  - requests>=2.25.0
  - librosa>=0.9.0
  - pip
  - pip:
    - torch